var result = {
	"addr": "",
	"ag_price": "",
	"c_unit": "元/公斤",
	"content": "",
	"craft_index": "13214",
	"craft_name": "山药",
	"craft_names": [],
	"currentPage": 1,
	"datas1": [3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 4.05, 4.5, 4.5, 4.92, 5.5],
	"datas2": [4.43, 4.05, 6.77, 7, 4.52, 4, 5.14, 9, 7.48, 6, 4.31, 0],
	"endRowNum": 10,
	"eud_id": "",
	"eud_name": "河南安阳豫北蔬菜批发市场",
	"eud_names": [],
	"eud_pic": "",
	"firstPage": 1,
	"get_p_date": "",
	"id": "",
	"isprod_mark": "",
	"lastPage": 1,
	"like_wise": "",
	"link_man": "",
	"multipartRequestHandler": null,
	"nextPage": 1,
	"p_index": "",
	"p_name": "",
	"pageCount": 0,
	"pageSize": 20,
	"par_craft_index": "",
	"priviousPage": 1,
	"promulgate_date": "",
	"recordCount": -1,
	"requestPage": 1,
	"servletWrapper": {},
	"site_url": "",
	"startRowNum": 0,
	"todayPrice": 0,
	"yesterdayPrice": 0
};