
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/daas?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#    url: jdbc:mysql://116.85.20.51:3306/daas?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 100
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 114.116.24.215
    port: 6379
    jedis:
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
    timeout: 30000
  kafka:
    consumer:
      enable-auto-commit: true
      group-id: demo
      auto-offset-reset: earliest
      bootstrap-servers: 114.116.24.215:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    bootstrap-servers: 114.116.24.215:9092

kafka:
  consumer:
    zookeeper:
      connect: 114.116.24.215:2181
      servers: 10.93.21.21:9092
      enable:
        auto:
          commit: true
    enable-auto-commit: true
    session:
      timeout: 6000
    auto:
      commit:
        interval: 100
    auto-offset-reset: latest
    topic: test
    group-id: test
    concurrency: 10
  producer:
    servers: 114.116.24.215:9092
    retries: 0
    batch-size: 4096
    linger: 1
    buffer-memory: 40960
mybatis:
  type-aliases-package: org.centralplains.daas.beans
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    org.centralplains.daas.dao: debug
server:
  port: 8000
